# Generated by Django 5.2.7 on 2025-10-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('content_html', models.TextField()),
                ('source_file', models.CharField(max_length=300)),
                ('source_format', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('content_html', models.TextField()),
                ('content_markdown_path', models.CharField(max_length=300)),
            ],
        ),
    ]
